name: Build and Deploy to AWS EKS

on:
  push:
    branches:
      - main  # Replace 'main' with your main branch name

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ankitha2504 }}
          password: ${{ secrets.Kuma9014813 }}

      - name: Build Docker image
        run: |
          docker build -t ankitha2504/react-frontend .
          docker push ankitha2504/react-frontend
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for improved Docker build performance

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIAQ3EGPTEJKHHYU7XV }}
          aws-secret-access-key: ${{ secrets.MTPyBYNn/Tay1MIL3E8aUbdY8aXbtiW1BEdgxDU2 }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name dev

      - name: Deploy to AWS EKS
        run: |
          kubectl get ns
          kubectl apply -f deployment.yaml  --validate=false
          kubectl apply -f service.yaml  --validate=false   
